apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-first-app
  template:
    metadata:
      labels:
        app: my-first-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: my-first-app
          #image: quay.io/rhdevelopers/my-first-app
          #image: my-first-app:1.0
          image: ghcr.io/vlogging664/my-first-app:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
